export const  Add_user='Add_user';
export const User_login = 'User_login';
export const ssc_add = 'ssc_add';
export const sscdetail ='sscdetail';
export const hscadd = 'hscadd';
export const graduation_add = 'graduation_add';
export const postgradd = 'postgradd';
export const contactdetail = 'contactdetail';
export const addskill = 'addskill';